export {default as Header } from './Header'
export {default as SearchBar } from './SearchBar'
export {default as Icons } from './Icons'
export {default as Loader} from './Loader'
export {default as Banners} from './Banners'
export {default as FeaturedHealth} from './FeaturedHealth'
export {default as LabTest} from './LabTest'
export {default as Achievement} from './Achievement'
export {default as LifeStyle} from './LifeStyle'
export {default as HealthCheck} from './HealthCheck'
export {default as UsersFeedback} from './UsersFeedback'
export {default as HowItWorks} from './HowItWorks'
export {default as SafeLab} from './SafeLab'